### ISSUE TITLE
Concept

### ISSUE THREAD

**Issue by SOS-Bob** [SOS-Bob/Punch-vest#1]

**Comment by SOS-Bob** [comment]
1. aim
- working, lasting, heavy duty punch vest
- reasonable costs
- easy to connect to games
- show off to other nerds
2. ways to get there
- plan, ask, decide, do
- buy parts
- assemble
- script
- set up server
- integrate to Armacom
- test
- publish
3. team
- looking for participants in all areas, also people to make theimselves a vest 
- now some knowledge: concept, Arma script, assembly, server setup
- now few knowledge: Arduino script, electronics, Armacom
4. make vest
5. play and show off

**Comment by SOS-Bob** [comment]
This is a start of Punch-vest Github. Welcome to join, add your knowledge or just follow and comment.

**Comment by SOS-Bob** [comment]
**Hit points**
![vest_front_hit_points1](https://user-images.githubusercontent.com/13051278/147386663-b1bf86c8-1abf-447a-971f-7d43eceacc6d.jpg)
![vest_back_hit_points1](https://user-images.githubusercontent.com/13051278/147386669-b1f79459-de8a-46e4-8771-baa6970ae115.jpg)


End unit is attached inside the vest, which is kept tight. A mild punch is formed. Attach points: neck(head), back middle(back), side low right(right leg), back low left(left leg), chest middle(chest, two valves for effect), left shoulder(left hand), right shoulder(right hand)

**Data handling**

program lines to init.sqf using this:

this addEventHandler ["HandleDamage", {
    params ["_unit", "_selection", "_damage", "_source", "_projectile", "_hitIndex", "_instigator", "_hitPoint"];
}];


From this discussion I have picked up code and used it in my scripts to regulate damage of body parts. Pretty easy to place armacom commands there as well.
https://forums.bistudio.com/forums/topic/198136-reducing-player-damage/

from Arma hitPointDamage made more simple first:

"face_hub"
"neck"
"head" = head

"pelvis"
"body" = chest(2 valves)

"spine1"
"spine2"
"spine3" = back

"left arms"
"left hand" = left hand

"right arms"
"right hand" = right hand

"left leg" = left leg

"right leg" = right leg

program Arduino:
- Armacom input from computer according to the hitpoint above -> ide program -> output from port to 1 of 8 valves leading to the end units mentioned above

**Comment by SOS-Bob** [comment]
**Punch unit**
![impact_description](https://user-images.githubusercontent.com/13051278/147386984-b489f6f8-8e65-4401-94ba-1db749e79fde.jpg)

**Comment by SOS-Bob** [comment]
Question: How do you find the concept and implementation?

**Comment by FatLurch** [comment]
> **Hit points**
> ![vest_front_hit_points1](https://user-images.githubusercontent.com/13051278/147386663-b1bf86c8-1abf-447a-971f-7d43eceacc6d.jpg)
> ![vest_back_hit_points1](https://user-images.githubusercontent.com/13051278/147386669-b1f79459-de8a-46e4-8771-baa6970ae115.jpg)
> 
> 
> End unit is attached inside the vest, which is kept tight. A mild punch is formed. Attach points: neck(head), back middle(back), side low right(right leg), back low left(left leg), chest middle(chest, two valves for effect), left shoulder(left hand), right shoulder(right hand)
> 
> **Data handling**
> 
> program lines to init.sqf using this:
> 
> this addEventHandler ["HandleDamage", {
>     params ["_unit", "_selection", "_damage", "_source", "_projectile", "_hitIndex", "_instigator", "_hitPoint"];
> }];
> 
> 
> From this discussion I have picked up code and used it in my scripts to regulate damage of body parts. Pretty easy to place armacom commands there as well.
> https://forums.bistudio.com/forums/topic/198136-reducing-player-damage/
> 
> from Arma hitPointDamage made more simple first:
> 
> "face_hub"
> "neck"
> "head" = head
> 
> "pelvis"
> "body" = chest(2 valves)
> 
> "spine1"
> "spine2"
> "spine3" = back
> 
> "left arms"
> "left hand" = left hand
> 
> "right arms"
> "right hand" = right hand
> 
> "left leg" = left leg
> 
> "right leg" = right leg
> 
> program Arduino:
> - Armacom input from computer according to the hitpoint above -> ide program -> output from port to 1 of 8 valves leading to the end units mentioned above
> 

Do these hit points align with the available hit points in ARMA itself?

You could use the attachTo command to attach spheres to the named body positions on a character to evaluate in ARMA.

**Comment by SOS-Bob** [comment]
The Arma hit points of men are many, but if I understand right, divided in these cathegories of which can be used in event handler, I have altered a bit them in the 'initPlayerLocal.sqf' for the suit's purposes.   

// Infantry selections
// Keep in mind that if revive is enabled then incapacitation may occur at around 0.7 damage.
// "": The overall damage that determines the damage value of the unit. Unit dies at damage equal to or above 1
// "face_hub": Unit dies at damage equal to or above 1
// "neck": Unit dies at damage equal to or above 1
// "head": Unit dies at damage equal to or above 1
// "pelvis": Unit dies at damage equal to or above 1
// "spine1": Unit dies at damage equal to or above 1
// "spine2": Unit dies at damage equal to or above 1
// "spine3": Unit dies at damage equal to or above 1
// "body": Unit dies at damage equal to or above 1
// "arms": Unit doesn't die with damage to this part
// "hands": Unit doesn't die with damage to this part
// "legs": Unit doesn't die with damage to this part

**Comment by SOS-Bob** [comment]
// Infantry selections
// Keep in mind that if revive is enabled then incapacitation may occur at around 0.7 damage.
// "": The overall damage that determines the damage value of the unit. Unit dies at damage equal to or above 1
// "face_hub": Unit dies at damage equal to or above 1
// "neck": Unit dies at damage equal to or above 1
// "head": Unit dies at damage equal to or above 1
// "pelvis": Unit dies at damage equal to or above 1
// "spine1": Unit dies at damage equal to or above 1
// "spine2": Unit dies at damage equal to or above 1
// "spine3": Unit dies at damage equal to or above 1
// "body": Unit dies at damage equal to or above 1
// "arms": Unit doesn't die with damage to this part
// "hands": Unit doesn't die with damage to this part
// "legs": Unit doesn't die with damage to this part

**Comment by SOS-Bob** [comment]
After everything works then I will make this a mod so it will work in all missions without messing with the scripts.

**Comment by SOS-Bob** [comment]
Hardware fixed. In software rest of the challenges.

**Comment by SOS-Bob** [comment]
Idea is not changed but implemention is. Changing gear to pneumatic which means heavier equipment. Just want to do this proper. Keeping in mind a light version with electric pads.

**Comment by SOS-Bob** [comment]
Yea, this is done. 
https://youtu.be/u1dDI9aU8OU?list=PLysuWIfOOnr6Smt1bUuGRWYQ9NM-PoumB
