### ISSUE TITLE
Parts

### ISSUE THREAD

**Issue by SOS-Bob** [SOS-Bob/Punch-vest#2]

**Comment by SOS-Bob** [comment]
Parts ordered.
![electromagnet](https://user-images.githubusercontent.com/13051278/147648151-edec2841-6f9f-4392-b95d-9abfc9eb20ce.jpg)
![magnet](https://user-images.githubusercontent.com/13051278/147675654-e324aeb3-9170-49ae-bb6d-adfa4f36d223.jpg)
![ESP32](https://user-images.githubusercontent.com/13051278/147648152-427003e4-8777-416b-b869-797ea24a0da8.png)
![regulator module](https://user-images.githubusercontent.com/13051278/147648157-c972ad85-0580-47a9-ae6d-fd128024d062.png)
![relay module](https://user-images.githubusercontent.com/13051278/147648159-5acfb0e5-1db9-428c-a495-9fa3e308e9bb.png)
![Battery](https://user-images.githubusercontent.com/13051278/147648160-d451b30d-4b7b-4368-99f2-12bbf94560a4.jpg)
![can](https://user-images.githubusercontent.com/13051278/147684494-d40ee816-7f5c-4080-af49-3d77a40592c7.jpg)
![specs](https://user-images.githubusercontent.com/13051278/147675668-876d5c75-dff6-4e68-9081-03c9f7944b96.png)
![flag](https://user-images.githubusercontent.com/13051278/147648154-dbb22b3d-93bb-419d-84d4-f6d545683d6c.jpg)
![molle_attachments](https://user-images.githubusercontent.com/13051278/147648155-357427cc-7a92-41be-a031-3db14c1c0379.jpg)
![pouch](https://user-images.githubusercontent.com/13051278/147648156-632363ab-4ba6-4b2a-b76f-3c4ae5b41322.jpg)
![belt](https://user-images.githubusercontent.com/13051278/147648148-b357a5b0-0f2e-4bad-b32f-3b6bf8e5aa30.jpg)

**Comment by SOS-Bob** [comment]
**Vest**
![vest1](https://user-images.githubusercontent.com/13051278/147386600-bfbd37a5-4d1a-4bba-a0b8-75dcd7ace3d6.jpg)
![vest2](https://user-images.githubusercontent.com/13051278/147386605-a056c5d9-9c85-4adb-8a25-c135ad8c6d90.jpg)
![vest3](https://user-images.githubusercontent.com/13051278/147386606-4677ac85-6d87-403a-b98d-050d5faa0e1a.jpg)
![vest4](https://user-images.githubusercontent.com/13051278/147386609-ebb01c45-00f6-4627-90df-6215b38b93e6.jpg)
![vest5](https://user-images.githubusercontent.com/13051278/147386613-a0a8769a-352e-46c4-97e4-bf3bddbf0b9d.jpg)
![vest6](https://user-images.githubusercontent.com/13051278/147386615-aab6326c-753f-4292-8ce8-aeae494a14bf.jpg)

**Comment by SOS-Bob** [comment]
Comments about the parts?

**Comment by SOS-Bob** [comment]
Please comment if you find a better solution or if you think there might be some problem with this setup. Ordering parts after next Armacom update.

**Comment by SOS-Bob** [comment]
Is the 12V (strength 1kg?), movement 10mm powerful, fast and reaching enough?

**Comment by SOS-Bob** [comment]
Maybe an Arduino model with more pins(some for future dev). For example Nano V3 Pro Mini Atmega328?

**Comment by FatLurch** [comment]
I'd recommend an ESP32 as the control board. It's programmed in the Arduino environment and features WiFi. The regular Arduino will work, you'll just be "tethered".

You could also run the solenoids off of an 11.1V LiPo battery as an option. If you go this route, you'll need a 5VDC regulator board for the ESP32.

**Comment by FatLurch** [comment]
> Is the 12V (strength 1kg?), movement 10mm powerful, fast and reaching enough? 
> 

This is beyond my expertise, sorry. 

You may want try try a couple of different types then procure 7 more of the best one later.

**Comment by SOS-Bob** [comment]
Great, cheers. Including battery pack just gives the vest more 'substance'. And going to refridgerator easier. First thought of doing this with air pressure but visualizing a compressor starting in a flat 2am make solenoid version sound a bit better.

**Comment by SOS-Bob** [comment]
Parts:

Geekcreit® ESP32 WiFi+bluetooth Development Board Ultra-Low Power Consumption Dual Cores Pins Unsoldered

3pcs MP1584 5V Buck Converter 4.5-24V Adjustable Step Down Regulator Module with Switch OPEN-SMART for Arduino

8 Channel 24V Relay Module High And Low Level Trigger BESTEP for Arduino

24v 12000mAh DC Rechargeable Li-ion Battery Portable Power Pack - UK

Permanent Magnets Sale Custom Electromagnet 12v 24v Powerfull Super Strong Neodymium Small Magnet
8 Pieces

Neodymium Magnet N50 Countersunk Ring Round
N35 35x5-6mm
8.00 Pieces

Mil-Tec Modular System Carrier

Mil-Tec Modular System pockets

Belgin M-1971 belt

Flag

BlackHawk MOLLE-Speed Clips 5"

Spray paint Dark Brown

**Comment by FatLurch** [comment]
You may want to grab some hookup wires to go between the ESP32 and the relay board (if you don't have them already)

**Comment by SOS-Bob** [comment]
Thanks, I think I have all kinds of, just waiting to be used.

ke 29. jouluk. 2021 klo 16.58 Erik ***@***.***) kirjoitti:

**Comment by SOS-Bob** [comment]
Waiting for parts.

**Comment by SOS-Bob** [comment]
Updating this soon with pneumatic version gear.

**Comment by SOS-Bob** [comment]
Yea, this is done. 
https://youtu.be/u1dDI9aU8OU?list=PLysuWIfOOnr6Smt1bUuGRWYQ9NM-PoumB
